name: quick_cart
description: "An innovative ecommerse mobile app developed with microservices architecture"


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.0
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  multiavatar: ^0.1.5
  flutter_svg: ^2.0.10+1
  file_picker: ^8.0.0+1
  loading_animation_widget: ^1.2.1
  khalti_flutter: ^3.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/
    - .env
    - .gitignore

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900